// Generated by https://quicktype.io

export interface Client {
    _id:      string;
    name:     string;
    surname:  string;
    email:    string;
    password: string;
    avatar:   string;
    isDev:    boolean;
    social:   Social;
    info:     Info;
    __v:      number;
    orders:   string[];
}

export interface Info {
    organization: string;
    time_zone:    string;
    language:     string[];
    _id:          string;
}

export interface Social {
    linkedin:  string;
    portfolio: string;
    github:    string;
    _id:       string;
}
