// Generated by https://quicktype.io

export interface Team {
    _id:          string;
    devs:         Dev[];
    language:     string[];
    isComplete:   boolean;
    time_zone:    string[];
    working:      boolean;
    availability: string;
    __v:          number;
    stack:        string;
}

export interface Dev {
    _id:         string;
    name:        string;
    surname:     string;
    email:       string;
    password:    string;
    role:        string;
    avatar:      string;
    isDev:       boolean;
    social:      Social;
    info:        Info;
    oldTeams:    any[];
    __v:         number;
    currentTeam: string;
}

export interface Info {
    time_availability: string;
    time_zone:         string;
    experience:        number;
    language:          string[];
    _id:               string;
}

export interface Social {
    linkedin:  string;
    portfolio: string;
    github:    string;
    _id:       string;
}
